
###################################################
-- Master DATABASE
INSERT INTO `erp_services` (`id`, `name`, `alias`, `icon`, `financial_service_alias`, `status`, `created_by`, `updated_by`, `deleted_by`, `created_at`, `updated_at`, `deleted_at`, `type`) VALUES (NULL, 'Manufacturing Order', 'mo', NULL, 'jv', 'active', NULL, NULL, NULL, NULL, NULL, NULL, 'transaction');


###################################################
-- all databases

alter table `erp_so_items` add `pwo_qty` double(20, 6) not null default '0' after `order_qty`;
alter table `erp_so_items_history` add `pwo_qty` double(20, 6) not null default '0' after `order_qty`;

create table `erp_production_work_orders` (`id` bigint unsigned not null auto_increment primary key, `organization_id` bigint unsigned null, `group_id` bigint unsigned null, `company_id` bigint unsigned null, `location_id` bigint unsigned null, `book_id` bigint unsigned null, `book_code` varchar(255) null, `document_number` varchar(255) null, `station_wise_consumption` enum('yes', 'no') not null default 'no', `doc_number_type` enum('Auto', 'Manually') not null default 'Manually', `doc_reset_pattern` enum('Never', 'Yearly', 'Quarterly', 'Monthly') null, `doc_prefix` varchar(255) null, `doc_suffix` varchar(255) null, `doc_no` int null, `document_date` date null, `revision_number` varchar(255) not null default '0', `revision_date` date null, `reference_number` varchar(255) null, `approval_level` int not null default '1' comment 'current approval level', `remarks` text null, `document_status` varchar(255) null, `created_by` bigint unsigned null, `updated_by` bigint unsigned null, `deleted_by` bigint unsigned null, `created_at` timestamp null, `updated_at` timestamp null, `deleted_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `erp_production_work_orders` add constraint `erp_production_work_orders_location_id_foreign` foreign key (`location_id`) references `erp_stores` (`id`);
alter table `erp_production_work_orders` add constraint `erp_production_work_orders_book_id_foreign` foreign key (`book_id`) references `erp_books` (`id`);
create table `erp_production_work_orders_history` (`id` bigint unsigned not null auto_increment primary key, `source_id` bigint unsigned null, `organization_id` bigint unsigned null, `group_id` bigint unsigned null, `company_id` bigint unsigned null, `location_id` bigint unsigned null, `book_id` bigint unsigned null, `book_code` varchar(255) null, `document_number` varchar(255) null, `station_wise_consumption` enum('yes', 'no') not null default 'no', `doc_number_type` enum('Auto', 'Manually') not null default 'Manually', `doc_reset_pattern` enum('Never', 'Yearly', 'Quarterly', 'Monthly') null, `doc_prefix` varchar(255) null, `doc_suffix` varchar(255) null, `doc_no` int null, `document_date` date null, `revision_number` varchar(255) not null default '0', `revision_date` date null, `reference_number` varchar(255) null, `approval_level` int not null default '1' comment 'current approval level', `remarks` text null, `document_status` varchar(255) null, `created_by` bigint unsigned null, `updated_by` bigint unsigned null, `deleted_by` bigint unsigned null, `created_at` timestamp null, `updated_at` timestamp null, `deleted_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `erp_production_work_orders_history` add constraint `erp_production_work_orders_history_source_id_foreign` foreign key (`source_id`) references `erp_production_work_orders` (`id`);
alter table `erp_production_work_orders_history` add constraint `erp_production_work_orders_history_location_id_foreign` foreign key (`location_id`) references `erp_stores` (`id`);
alter table `erp_production_work_orders_history` add constraint `erp_production_work_orders_history_book_id_foreign` foreign key (`book_id`) references `erp_books` (`id`);
create table `erp_pwo_items` (`id` bigint unsigned not null auto_increment primary key, `pwo_id` bigint unsigned null comment 'erp_production_work_orders id', `item_id` bigint unsigned null, `item_code` varchar(255) null, `item_name` varchar(255) null, `hsn_id` bigint unsigned null, `hsn_code` varchar(255) null, `uom_id` bigint unsigned null, `uom_code` varchar(255) null, `order_qty` decimal(15, 2) not null default '0', `manf_order_qty` decimal(15, 2) not null default '0', `inventory_uom_id` bigint unsigned null, `inventory_uom_code` varchar(255) null, `inventory_uom_qty` decimal(15, 2) not null default '0', `created_at` timestamp null, `updated_at` timestamp null, `deleted_at` timestamp null, `created_by` bigint unsigned null, `updated_by` bigint unsigned null, `deleted_by` bigint unsigned null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `erp_pwo_items` add constraint `erp_pwo_items_pwo_id_foreign` foreign key (`pwo_id`) references `erp_production_work_orders` (`id`);
alter table `erp_pwo_items` add constraint `erp_pwo_items_item_id_foreign` foreign key (`item_id`) references `erp_items` (`id`) ; 
alter table `erp_pwo_items` add constraint `erp_pwo_items_hsn_id_foreign` foreign key (`hsn_id`) references `erp_hsns` (`id`) ;
alter table `erp_pwo_items` add constraint `erp_pwo_items_uom_id_foreign` foreign key (`uom_id`) references `erp_units` (`id`) ; 
alter table `erp_pwo_items` add constraint `erp_pwo_items_inventory_uom_id_foreign` foreign key (`inventory_uom_id`) references `erp_units` (`id`);
create table `erp_pwo_items_history` (`id` bigint unsigned not null auto_increment primary key, `source_id` bigint unsigned null, `pwo_id` bigint unsigned null comment 'erp_production_work_orders id', `item_id` bigint unsigned null, `item_code` varchar(255) null, `item_name` varchar(255) null, `hsn_id` bigint unsigned null, `hsn_code` varchar(255) null, `uom_id` bigint unsigned null, `uom_code` varchar(255) null, `order_qty` decimal(15, 2) not null default '0', `manf_order_qty` decimal(15, 2) not null default '0', `inventory_uom_id` bigint unsigned null, `inventory_uom_code` varchar(255) null, `inventory_uom_qty` decimal(15, 2) not null default '0', `created_at` timestamp null, `updated_at` timestamp null, `deleted_at` timestamp null, `created_by` bigint unsigned null, `updated_by` bigint unsigned null, `deleted_by` bigint unsigned null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'  ;
alter table `erp_pwo_items_history` add constraint `erp_pwo_items_history_source_id_foreign` foreign key (`source_id`) references `erp_pwo_items` (`id`)  ;
alter table `erp_pwo_items_history` add constraint `erp_pwo_items_history_pwo_id_foreign` foreign key (`pwo_id`) references `erp_production_work_orders_history` (`id`)  ;
alter table `erp_pwo_items_history` add constraint `erp_pwo_items_history_item_id_foreign` foreign key (`item_id`) references `erp_items` (`id`)  ;
alter table `erp_pwo_items_history` add constraint `erp_pwo_items_history_hsn_id_foreign` foreign key (`hsn_id`) references `erp_hsns` (`id`)  ;
alter table `erp_pwo_items_history` add constraint `erp_pwo_items_history_uom_id_foreign` foreign key (`uom_id`) references `erp_units` (`id`)  ;
alter table `erp_pwo_items_history` add constraint `erp_pwo_items_history_inventory_uom_id_foreign` foreign key (`inventory_uom_id`) references `erp_units` (`id`)  ;
create table `erp_pwo_item_attributes` (`id` bigint unsigned not null auto_increment primary key, `pwo_id` bigint unsigned null, `pwo_item_id` bigint unsigned null, `item_attribute_id` bigint unsigned null comment 'use tbl erp_item_attributes', `item_id` bigint unsigned null, `item_code` varchar(255) null, `attribute_group_id` bigint unsigned null, `attribute_id` bigint unsigned null, `attribute_name` varchar(255) null, `attribute_value` varchar(255) null, `created_at` timestamp null, `updated_at` timestamp null, `deleted_at` timestamp null, `created_by` bigint unsigned null, `updated_by` bigint unsigned null, `deleted_by` bigint unsigned null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'  ;
alter table `erp_pwo_item_attributes` add constraint `erp_pwo_item_attributes_pwo_id_foreign` foreign key (`pwo_id`) references `erp_production_work_orders` (`id`)  ;
alter table `erp_pwo_item_attributes` add constraint `erp_pwo_item_attributes_pwo_item_id_foreign` foreign key (`pwo_item_id`) references `erp_pwo_items` (`id`)  ;
alter table `erp_pwo_item_attributes` add constraint `erp_pwo_item_attributes_item_id_foreign` foreign key (`item_id`) references `erp_items` (`id`)  ;
alter table `erp_pwo_item_attributes` add constraint `erp_pwo_item_attributes_attribute_id_foreign` foreign key (`attribute_id`) references `erp_attributes` (`id`)  ;
alter table `erp_pwo_item_attributes` add constraint `erp_pwo_item_attributes_item_attribute_id_foreign` foreign key (`item_attribute_id`) references `erp_item_attributes` (`id`)  ;
create table `erp_pwo_item_attributes_history` (`id` bigint unsigned not null auto_increment primary key, `source_id` bigint unsigned null, `pwo_id` bigint unsigned null, `pwo_item_id` bigint unsigned null, `item_attribute_id` bigint unsigned null comment 'use tbl erp_item_attributes', `item_id` bigint unsigned null, `item_code` varchar(255) null, `attribute_group_id` bigint unsigned null, `attribute_id` bigint unsigned null, `attribute_name` varchar(255) null, `attribute_value` varchar(255) null, `created_at` timestamp null, `updated_at` timestamp null, `deleted_at` timestamp null, `created_by` bigint unsigned null, `updated_by` bigint unsigned null, `deleted_by` bigint unsigned null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'  ;
alter table `erp_pwo_item_attributes_history` add constraint `erp_pwo_item_attributes_history_source_id_foreign` foreign key (`source_id`) references `erp_pwo_item_attributes` (`id`)  ;
alter table `erp_pwo_item_attributes_history` add constraint `erp_pwo_item_attributes_history_pwo_id_foreign` foreign key (`pwo_id`) references `erp_production_work_orders_history` (`id`)  ;
alter table `erp_pwo_item_attributes_history` add constraint `erp_pwo_item_attributes_history_item_id_foreign` foreign key (`item_id`) references `erp_items` (`id`)  ;
alter table `erp_pwo_item_attributes_history` add constraint `erp_pwo_item_attributes_history_pwo_item_id_foreign` foreign key (`pwo_item_id`) references `erp_pwo_items_history` (`id`)  ;
alter table `erp_pwo_item_attributes_history` add constraint `erp_pwo_item_attributes_history_item_attribute_id_foreign` foreign key (`item_attribute_id`) references `erp_item_attributes` (`id`)  ;
alter table `erp_pwo_item_attributes_history` add constraint `erp_pwo_item_attributes_history_attribute_id_foreign` foreign key (`attribute_id`) references `erp_attributes` (`id`)  ;
create table `erp_pwo_media` (`id` bigint unsigned not null auto_increment primary key, `model_type` varchar(255) not null, `model_id` bigint unsigned not null, `uuid` char(36) null, `model_name` varchar(255) not null, `collection_name` varchar(255) not null, `name` varchar(255) not null, `file_name` varchar(255) not null, `mime_type` varchar(255) null, `disk` varchar(255) not null, `conversions_disk` varchar(255) null, `size` bigint unsigned not null, `manipulations` json not null, `custom_properties` json not null, `generated_conversions` json not null, `responsive_images` json not null, `order_column` int unsigned null, `created_at` timestamp null, `updated_at` timestamp null, `deleted_at` timestamp null, `created_by` bigint unsigned null, `updated_by` bigint unsigned null, `deleted_by` bigint unsigned null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'  ;
create table `erp_pwo_so_mapping` (`id` bigint unsigned not null auto_increment primary key, `pwo_id` bigint unsigned null, `so_id` bigint unsigned not null, `so_item_id` bigint unsigned not null, `item_id` bigint unsigned not null, `item_code` varchar(255) not null, `attributes` json null, `uom_id` bigint unsigned null, `uom_code` varchar(255) null, `qty` decimal(20, 6) not null default '0', `mo_product_qty` double(20, 6) not null default '0', `mo_value` double(20, 6) not null default '0', `pslip_qty` double(20, 6) not null default '0', `inventory_uom_id` bigint unsigned null, `inventory_uom_code` varchar(255) null, `inventory_uom_qty` double(20, 6) not null default '0', `created_by` bigint unsigned null, `updated_by` bigint unsigned null, `deleted_by` bigint unsigned null, `created_at` timestamp null, `updated_at` timestamp null, `deleted_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'  ;
alter table `erp_pwo_so_mapping` add constraint `erp_pwo_so_mapping_so_id_foreign` foreign key (`so_id`) references `erp_sale_orders` (`id`) on delete cascade  ;
alter table `erp_pwo_so_mapping` add constraint `erp_pwo_so_mapping_so_item_id_foreign` foreign key (`so_item_id`) references `erp_so_items` (`id`) on delete cascade  ;
alter table `erp_pwo_so_mapping` add constraint `erp_pwo_so_mapping_item_id_foreign` foreign key (`item_id`) references `erp_items` (`id`) on delete cascade  ;
alter table `erp_pwo_so_mapping` add constraint `erp_pwo_so_mapping_pwo_id_foreign` foreign key (`pwo_id`) references `erp_production_work_orders` (`id`) on delete set null  ;
create table `erp_pwo_so_mapping_history` (`id` bigint unsigned not null auto_increment primary key, `source_id` bigint unsigned null, `pwo_id` bigint unsigned null, `so_id` bigint unsigned not null, `so_item_id` bigint unsigned not null, `item_id` bigint unsigned not null, `item_code` varchar(255) not null, `attributes` json null, `uom_id` bigint unsigned null, `uom_code` varchar(255) null, `qty` decimal(20, 6) not null default '0', `mo_product_qty` double(20, 6) not null default '0', `mo_value` double(20, 6) not null default '0', `pslip_qty` double(20, 6) not null default '0', `inventory_uom_id` bigint unsigned null, `inventory_uom_code` varchar(255) null, `inventory_uom_qty` double(20, 6) not null default '0', `created_by` bigint unsigned null, `updated_by` bigint unsigned null, `deleted_by` bigint unsigned null, `created_at` timestamp null, `updated_at` timestamp null, `deleted_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'  ;
alter table `erp_pwo_so_mapping_history` add constraint `erp_pwo_so_mapping_history_so_id_foreign` foreign key (`so_id`) references `erp_sale_orders` (`id`) on delete cascade  ;
alter table `erp_pwo_so_mapping_history` add constraint `erp_pwo_so_mapping_history_so_item_id_foreign` foreign key (`so_item_id`) references `erp_so_items` (`id`) on delete cascade  ;
alter table `erp_pwo_so_mapping_history` add constraint `erp_pwo_so_mapping_history_item_id_foreign` foreign key (`item_id`) references `erp_items` (`id`) on delete cascade  ;
alter table `erp_pwo_so_mapping_history` add constraint `erp_pwo_so_mapping_history_pwo_id_foreign` foreign key (`pwo_id`) references `erp_production_work_orders` (`id`) on delete set null  ;
create table `erp_pwo_station_consumptions` (`id` bigint unsigned not null auto_increment primary key, `pwo_mapping_id` bigint unsigned null, `station_id` bigint unsigned null, `mo_product_qty` double(20, 6) not null default '0', `mo_value` double(20, 6) not null default '0', `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'  ;
alter table `erp_pwo_station_consumptions` add constraint `erp_pwo_station_consumptions_pwo_mapping_id_foreign` foreign key (`pwo_mapping_id`) references `erp_pwo_so_mapping` (`id`)  ;
create table `erp_pwo_station_consumptions_history` (`id` bigint unsigned not null auto_increment primary key, `source_id` bigint unsigned null, `pwo_mapping_id` bigint unsigned null, `station_id` bigint unsigned null, `mo_product_qty` double(20, 6) not null default '0', `mo_value` double(20, 6) not null default '0', `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'  ;
alter table `erp_pwo_so_mapping` add `current_level` int not null default '1' after `inventory_uom_qty`  ;
alter table `erp_pwo_station_consumptions` add `level` int not null default '1' after `mo_value`  ;
alter table `erp_pwo_station_consumptions_history` add `level` int not null default '1' after `mo_value`;

create table `erp_mfg_orders` (`id` bigint unsigned not null auto_increment primary key, `store_id` bigint unsigned null, `station_id` bigint unsigned null, `organization_id` bigint unsigned null, `group_id` bigint unsigned null, `company_id` bigint unsigned null, `book_id` bigint unsigned null comment 'books tbl id', `book_code` varchar(255) null, `document_number` varchar(255) null, `document_date` date null, `doc_number_type` enum('Auto', 'Manually') not null default 'Manually', `doc_reset_pattern` enum('Never', 'Yearly', 'Quarterly', 'Monthly') null, `doc_prefix` varchar(255) null, `doc_suffix` varchar(255) null, `doc_no` int null, `document_status` varchar(255) null, `revision_number` int not null default '0', `revision_date` date null, `remarks` text null, `approval_level` int not null default '1' comment 'Current Approval Level', `currency_id` bigint unsigned null, `currency_code` varchar(255) null, `org_currency_id` bigint unsigned null, `org_currency_code` varchar(255) null, `org_currency_exg_rate` decimal(15, 6) null, `comp_currency_id` bigint unsigned null, `comp_currency_code` varchar(255) null, `comp_currency_exg_rate` decimal(15, 6) null, `group_currency_id` bigint unsigned null, `group_currency_code` varchar(255) null, `group_currency_exg_rate` decimal(15, 6) null, `created_by` bigint unsigned null, `updated_by` bigint unsigned null, `deleted_by` bigint unsigned null, `created_at` timestamp null, `updated_at` timestamp null, `deleted_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `erp_mfg_orders` add constraint `erp_mfg_orders_store_id_foreign` foreign key (`store_id`) references `erp_stores` (`id`) on delete cascade;
alter table `erp_mfg_orders` add constraint `erp_mfg_orders_station_id_foreign` foreign key (`station_id`) references `erp_stations` (`id`) on delete cascade;
create table `erp_mfg_orders_history` (`id` bigint unsigned not null auto_increment primary key, `source_id` bigint unsigned null, `store_id` bigint unsigned null, `station_id` bigint unsigned null, `organization_id` bigint unsigned null, `group_id` bigint unsigned null, `company_id` bigint unsigned null, `book_id` bigint unsigned null comment 'books tbl id', `book_code` varchar(255) null, `document_number` varchar(255) null, `document_date` date null, `doc_number_type` enum('Auto', 'Manually') not null default 'Manually', `doc_reset_pattern` enum('Never', 'Yearly', 'Quarterly', 'Monthly') null, `doc_prefix` varchar(255) null, `doc_suffix` varchar(255) null, `doc_no` int null, `document_status` varchar(255) null, `revision_number` int not null default '0', `revision_date` date null, `remarks` text null, `approval_level` int not null default '1' comment 'Current Approval Level', `currency_id` bigint unsigned null, `currency_code` varchar(255) null, `org_currency_id` bigint unsigned null, `org_currency_code` varchar(255) null, `org_currency_exg_rate` decimal(15, 6) null, `comp_currency_id` bigint unsigned null, `comp_currency_code` varchar(255) null, `comp_currency_exg_rate` decimal(15, 6) null, `group_currency_id` bigint unsigned null, `group_currency_code` varchar(255) null, `group_currency_exg_rate` decimal(15, 6) null, `created_by` bigint unsigned null, `updated_by` bigint unsigned null, `deleted_by` bigint unsigned null, `created_at` timestamp null, `updated_at` timestamp null, `deleted_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `erp_mfg_orders_history` add constraint `erp_mfg_orders_history_store_id_foreign` foreign key (`store_id`) references `erp_stores` (`id`) on delete cascade;
alter table `erp_mfg_orders_history` add constraint `erp_mfg_orders_history_station_id_foreign` foreign key (`station_id`) references `erp_stations` (`id`) on delete cascade;
create table `erp_mo_products` (`id` bigint unsigned not null auto_increment primary key, `mo_id` bigint unsigned null, `production_bom_id` bigint unsigned null comment 'erp_boms id', `item_id` bigint unsigned null, `customer_id` bigint unsigned null, `item_code` varchar(255) null, `uom_id` bigint unsigned null, `qty` double not null default '0', `pwo_mapping_id` bigint unsigned null, `order_id` bigint unsigned null, `remark` text null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `erp_mo_products` add constraint `erp_mo_products_mo_id_foreign` foreign key (`mo_id`) references `erp_mfg_orders` (`id`) on delete cascade;
create table `erp_mo_products_history` (`id` bigint unsigned not null auto_increment primary key, `source_id` bigint unsigned null, `mo_id` bigint unsigned null, `production_bom_id` bigint unsigned null comment 'erp_boms id', `item_id` bigint unsigned null, `customer_id` bigint unsigned null, `item_code` varchar(255) null, `uom_id` bigint unsigned null, `qty` double not null default '0', `pwo_mapping_id` bigint unsigned null, `order_id` bigint unsigned null, `remark` text null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `erp_mo_products_history` add constraint `erp_mo_products_history_mo_id_foreign` foreign key (`mo_id`) references `erp_mfg_orders_history` (`id`) on delete cascade;
create table `erp_mo_product_attributes` (`id` bigint unsigned not null auto_increment primary key, `mo_id` bigint unsigned null, `mo_product_id` bigint unsigned null, `item_attribute_id` bigint unsigned null, `item_code` varchar(255) null, `attribute_name` bigint unsigned null, `attribute_value` bigint unsigned null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `erp_mo_product_attributes` add constraint `erp_mo_product_attributes_mo_id_foreign` foreign key (`mo_id`) references `erp_mfg_orders` (`id`) on delete cascade;
alter table `erp_mo_product_attributes` add constraint `erp_mo_product_attributes_mo_product_id_foreign` foreign key (`mo_product_id`) references `erp_mo_products` (`id`) on delete cascade;
create table `erp_mo_product_attributes_history` (`id` bigint unsigned not null auto_increment primary key, `source_id` bigint unsigned null, `mo_id` bigint unsigned null, `mo_product_id` bigint unsigned null, `item_attribute_id` bigint unsigned null, `item_code` varchar(255) null, `attribute_name` bigint unsigned null, `attribute_value` bigint unsigned null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `erp_mo_product_attributes_history` add constraint `erp_mo_product_attributes_history_mo_id_foreign` foreign key (`mo_id`) references `erp_mfg_orders_history` (`id`) on delete cascade;
alter table `erp_mo_product_attributes_history` add constraint `erp_mo_product_attributes_history_mo_product_id_foreign` foreign key (`mo_product_id`) references `erp_mo_products_history` (`id`) on delete cascade;
create table `erp_mo_items` (`id` bigint unsigned not null auto_increment primary key, `mo_id` bigint unsigned null, `item_id` bigint unsigned null, `item_code` varchar(255) null, `uom_id` bigint unsigned null, `qty` double not null default '0', `rate` double not null default '0', `inventory_uom_id` bigint unsigned null, `inventory_uom_code` varchar(255) null, `inventory_uom_qty` double not null default '0', `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `erp_mo_items` add constraint `erp_mo_items_mo_id_foreign` foreign key (`mo_id`) references `erp_mfg_orders` (`id`) on delete cascade;
create table `erp_mo_items_history` (`id` bigint unsigned not null auto_increment primary key, `source_id` bigint unsigned null, `mo_id` bigint unsigned null, `item_id` bigint unsigned null, `item_code` varchar(255) null, `uom_id` bigint unsigned null, `qty` double not null default '0', `rate` double not null default '0', `inventory_uom_id` bigint unsigned null, `inventory_uom_code` varchar(255) null, `inventory_uom_qty` double not null default '0', `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `erp_mo_items_history` add constraint `erp_mo_items_history_mo_id_foreign` foreign key (`mo_id`) references `erp_mfg_orders_history` (`id`) on delete cascade;
create table `erp_mo_bom_mapping` (`id` bigint unsigned not null auto_increment primary key, `mo_id` bigint unsigned null, `mo_product_id` bigint unsigned null, `bom_id` bigint unsigned null, `bom_detail_id` bigint unsigned null, `item_id` bigint unsigned null, `item_code` varchar(255) null, `attributes` json null, `uom_id` bigint unsigned null, `qty` double not null default '0', `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `erp_mo_bom_mapping` add constraint `erp_mo_bom_mapping_mo_id_foreign` foreign key (`mo_id`) references `erp_mfg_orders` (`id`) on delete cascade;
alter table `erp_mo_bom_mapping` add constraint `erp_mo_bom_mapping_mo_product_id_foreign` foreign key (`mo_product_id`) references `erp_mo_products` (`id`) on delete cascade;
alter table `erp_mo_bom_mapping` add constraint `erp_mo_bom_mapping_bom_id_foreign` foreign key (`bom_id`) references `erp_boms` (`id`) on delete cascade;
alter table `erp_mo_bom_mapping` add constraint `erp_mo_bom_mapping_bom_detail_id_foreign` foreign key (`bom_detail_id`) references `erp_bom_details` (`id`) on delete cascade;
create table `erp_mo_bom_mapping_history` (`id` bigint unsigned not null auto_increment primary key, `source_id` bigint unsigned null, `mo_id` bigint unsigned null, `mo_product_id` bigint unsigned null, `bom_id` bigint unsigned null, `bom_detail_id` bigint unsigned null, `item_id` bigint unsigned null, `item_code` varchar(255) null, `attributes` json null, `uom_id` bigint unsigned null, `qty` double not null default '0', `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `erp_mo_bom_mapping_history` add constraint `erp_mo_bom_mapping_history_mo_id_foreign` foreign key (`mo_id`) references `erp_mfg_orders_history` (`id`) on delete cascade;
alter table `erp_mo_bom_mapping_history` add constraint `erp_mo_bom_mapping_history_mo_product_id_foreign` foreign key (`mo_product_id`) references `erp_mo_products_history` (`id`) on delete cascade;
alter table `erp_mo_bom_mapping_history` add constraint `erp_mo_bom_mapping_history_bom_id_foreign` foreign key (`bom_id`) references `erp_boms_history` (`id`) on delete cascade;
alter table `erp_mo_bom_mapping_history` add constraint `erp_mo_bom_mapping_history_bom_detail_id_foreign` foreign key (`bom_detail_id`) references `erp_bom_details_history` (`id`) on delete cascade;
create table `erp_mo_item_attributes` (`id` bigint unsigned not null auto_increment primary key, `mo_id` bigint unsigned null, `mo_item_id` bigint unsigned null, `item_id` bigint unsigned null, `item_attribute_id` bigint unsigned null comment 'use tbl erp_item_attributes', `item_code` varchar(255) null, `attribute_name` bigint unsigned null, `attribute_value` bigint unsigned null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `erp_mo_item_attributes` add constraint `erp_mo_item_attributes_mo_item_id_foreign` foreign key (`mo_item_id`) references `erp_mo_items` (`id`) on delete cascade;
alter table `erp_mo_item_attributes` add constraint `erp_mo_item_attributes_mo_id_foreign` foreign key (`mo_id`) references `erp_mfg_orders` (`id`) on delete cascade;
create table `erp_mo_item_attributes_history` (`id` bigint unsigned not null auto_increment primary key, `source_id` bigint unsigned null, `mo_id` bigint unsigned null, `mo_item_id` bigint unsigned null, `item_id` bigint unsigned null, `item_attribute_id` bigint unsigned null comment 'use tbl erp_item_attributes', `item_code` varchar(255) null, `attribute_name` bigint unsigned null, `attribute_value` bigint unsigned null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `erp_mo_item_attributes_history` add constraint `erp_mo_item_attributes_history_mo_item_id_foreign` foreign key (`mo_item_id`) references `erp_mo_items_history` (`id`) on delete cascade;
alter table `erp_mo_item_attributes_history` add constraint `erp_mo_item_attributes_history_mo_id_foreign` foreign key (`mo_id`) references `erp_mfg_orders_history` (`id`) on delete cascade;
create table `erp_mo_media` (`id` bigint unsigned not null auto_increment primary key, `model_type` varchar(255) not null, `model_id` bigint unsigned not null, `uuid` char(36) null, `model_name` varchar(255) not null, `collection_name` varchar(255) not null, `name` varchar(255) not null, `file_name` varchar(255) not null, `mime_type` varchar(255) null, `disk` varchar(255) not null, `conversions_disk` varchar(255) null, `size` bigint unsigned not null, `manipulations` json not null, `custom_properties` json not null, `generated_conversions` json not null, `responsive_images` json not null, `order_column` int unsigned null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `erp_mo_media` add index `erp_mo_media_model_type_model_id_index`(`model_type`, `model_id`);
alter table `erp_mo_media` add unique `erp_mo_media_uuid_unique`(`uuid`);
ALTER TABLE `erp_mo_media` ADD INDEX `erp_mo_media_order_column_index` (`order_column`);

ALTER TABLE erp_items ADD COLUMN storage_type VARCHAR(255) NULL AFTER service_type;

--all databases--
ALTER TABLE `erp_pwo_items` ADD `mi_qty` DOUBLE(20,6) NOT NULL DEFAULT '0' AFTER `manf_order_qty`;
ALTER TABLE `erp_pwo_items_history` ADD `mi_qty` DOUBLE(20,6) NOT NULL DEFAULT '0' AFTER `manf_order_qty`;

ALTER TABLE `erp_mo_items` ADD `mi_qty` DOUBLE(20,6) NOT NULL DEFAULT '0' AFTER `qty`;
ALTER TABLE `erp_mo_items_history` ADD `mi_qty` DOUBLE(20,6) NOT NULL DEFAULT '0' AFTER `qty`;

