<?php

namespace App\Helpers\TransactionReport;
use App\Models\Legal;

class bomReportHelper
{
    const BOM_TABLE_HEADERS = [
        [
            'name' => 'S. No',
            'field' => 'DT_RowIndex',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Series',
            'field' => 'book_code',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'BOM No',
            'field' => 'document_number',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'BOM Date',
            'field' => 'document_date',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Product Code',
            'field' => 'product_code',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Product Name',
            'field' => 'product_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Product Attributes',
            'field' => 'product_attributes',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Product UOM',
            'field' => 'product_uom',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Production Type',
            'field' => 'production_type',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Production Route',
            'field' => 'production_route',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Total Item Cost',
            'field' => 'product_cost',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Overheads',
            'field' => 'overhead_amount',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Total Value',
            'field' => 'total_cost',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Customizable ?',
            'field' => 'customizable',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Safety Buffer %',
            'field' => 'safety_buffer',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Item Code',
            'field' => 'item_code',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Item Name',
            'field' => 'item_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Item Attributes',
            'field' => 'item_attributes',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'UOM',
            'field' => 'item_uom',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Qty',
            'field' => 'item_qty',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Cost',
            'field' => 'item_cost',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Overheads',
            'field' => 'item_overhead',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Item Value',
            'field' => 'item_value',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Station',
            'field' => 'item_station',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Section',
            'field' => 'item_section',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Sub Section',
            'field' => 'item_sub_section',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Vendor',
            'field' => 'item_vendor',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Status',
            'field' => 'status',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => 'text-align:center',
            'column_style' => '',
        ],
    ];
    const BOM_FILTERS = [
        [
            'colSpan' => 'auto',
            'label' => 'BOM No',
            'id' => 'doc_number_filter',
            'requestName' => 'document_number',
            'term' => 'report_BOM_documents',
            'value_key' => 'id',
            'label_key' => 'document_number',
            'type' => 'input_text'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Product',
            'id' => 'doc_number_filter',
            'requestName' => 'product_id',
            'term' => 'report_products',
            'value_key' => 'id',
            'label_key' => 'item_name',
            'type' => 'auto_complete'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Item',
            'id' => 'item_filter',
            'requestName' => 'item_id',
            'term' => 'report_items',
            'value_key' => 'id',
            'label_key' => 'item_name',
            'type' => 'auto_complete'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Status',
            'id' => 'status',
            'requestName' => 'status',
            'term' => 'document_statuses',
            'value_key' => 'id',
            'label_key' => 'name',
            'type' => 'auto_complete'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Company',
            'id' => 'company_filter',
            'requestName' => 'company_id',
            'term' => 'companies',
            'value_key' => 'id',
            'label_key' => 'name',
            'type' => 'auto_complete',
            'dependent' => ['organization_filter']

        ],
        [
            'colSpan' => 'auto',
            'label' => 'Organization',
            'id' => 'organization_filter',
            'requestName' => 'organization_id',
            'term' => 'organizations',
            'value_key' => 'id',
            'label_key' => 'name',
            'type' => 'auto_complete',
            'dependent' => ['location_filter']
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Location',
            'id' => 'store_name',
            'requestName' => 'location_id',
            'term' => 'location',
            'value_key' => 'id',
            'label_key' => 'store_name',
            'type' => 'auto_complete'
        ],
        // [
        //     'colSpan' => 'auto',
        //     'label' => 'Store',
        //     'id' => 'name',
        //     'requestName' => 'store_id',
        //     'term' => 'sub_store',
        //     'value_key' => 'id',
        //     'label_key' => 'name',
        //     'type' => 'auto_complete',
        // ],
    ];
}
