CREATE TABLE `upload_customer_masters` (
  `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `company_name` VARCHAR(255) DEFAULT NULL,
  `customer_initial` VARCHAR(255) DEFAULT NULL,
  `customer_code` VARCHAR(255) DEFAULT NULL,
  `category` VARCHAR(255) DEFAULT NULL,
  `subcategory` VARCHAR(255) DEFAULT NULL,
  `currency` VARCHAR(255) DEFAULT NULL,
  `payment_term` VARCHAR(255) DEFAULT NULL,
  `customer_type` VARCHAR(255) DEFAULT NULL,
  `organization_type` VARCHAR(255) DEFAULT NULL,
  `sales_person` VARCHAR(255) DEFAULT NULL,
  `customer_code_type` VARCHAR(255) DEFAULT NULL,
  `country` VARCHAR(255) DEFAULT NULL,
  `state` VARCHAR(255) DEFAULT NULL,
  `city` VARCHAR(255) DEFAULT NULL,
  `address` VARCHAR(255) DEFAULT NULL,
  `pin_code` VARCHAR(255) DEFAULT NULL,
  `email` VARCHAR(255) DEFAULT NULL,
  `phone` VARCHAR(255) DEFAULT NULL,
  `mobile` VARCHAR(255) DEFAULT NULL,
  `whatsapp_number` VARCHAR(255) DEFAULT NULL,
  `notification_mode` VARCHAR(255) DEFAULT NULL,
  `pan_number` VARCHAR(255) DEFAULT NULL,
  `tin_number` VARCHAR(255) DEFAULT NULL,
  `aadhar_number` VARCHAR(255) DEFAULT NULL,
  `ledger_code` VARCHAR(255) DEFAULT NULL,
  `ledger_group` VARCHAR(255) DEFAULT NULL,
  `credit_limit` DECIMAL(15,2) DEFAULT NULL,
  `credit_days` INT DEFAULT NULL,
  `gst_applicable` VARCHAR(255) DEFAULT NULL,
  `gstin_no` VARCHAR(255) DEFAULT NULL,
  `gst_registered_name` VARCHAR(255) DEFAULT NULL,
  `gstin_registration_date` VARCHAR(255) DEFAULT NULL,
  `tds_applicable` VARCHAR(255) DEFAULT NULL,
  `wef_date` VARCHAR(255) DEFAULT NULL,
  `tds_certificate_no` VARCHAR(255) DEFAULT NULL,
  `tds_tax_percentage` DECIMAL(5,2) DEFAULT NULL,
  `tds_category` VARCHAR(255) DEFAULT NULL,
  `tds_value_cab` DECIMAL(15,2) DEFAULT NULL,
  `tan_number` VARCHAR(255) DEFAULT NULL,
  `status` VARCHAR(255) DEFAULT NULL,
  `group_id` BIGINT UNSIGNED DEFAULT NULL,
  `company_id` BIGINT UNSIGNED DEFAULT NULL,
  `organization_id` BIGINT UNSIGNED DEFAULT NULL,
  `remarks` TEXT DEFAULT NULL,
  `batch_no` VARCHAR(255) DEFAULT NULL,
  `user_id` BIGINT UNSIGNED DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
);


CREATE TABLE `upload_vendor_masters` (
  `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `company_name` VARCHAR(255) DEFAULT NULL,
  `vendor_initial` VARCHAR(255) DEFAULT NULL,
  `vendor_code` VARCHAR(255) DEFAULT NULL,
  `category` VARCHAR(255) DEFAULT NULL,
  `subcategory` VARCHAR(255) DEFAULT NULL,
  `currency` VARCHAR(255) DEFAULT NULL,
  `payment_term` VARCHAR(255) DEFAULT NULL,
  `vendor_type` VARCHAR(255) DEFAULT NULL,
  `vendor_sub_type` VARCHAR(255) DEFAULT NULL,
  `organization_type` VARCHAR(255) DEFAULT NULL,
  `vendor_code_type` VARCHAR(255) DEFAULT NULL,
  `country` VARCHAR(255) DEFAULT NULL,
  `state` VARCHAR(255) DEFAULT NULL,
  `city` VARCHAR(255) DEFAULT NULL,
  `address` VARCHAR(255) DEFAULT NULL,
  `pin_code` VARCHAR(255) DEFAULT NULL,
  `email` VARCHAR(255) DEFAULT NULL,
  `phone` VARCHAR(255) DEFAULT NULL,
  `mobile` VARCHAR(255) DEFAULT NULL,
  `whatsapp_number` VARCHAR(255) DEFAULT NULL,
  `notification_mode` VARCHAR(255) DEFAULT NULL,
  `pan_number` VARCHAR(255) DEFAULT NULL,
  `tin_number` VARCHAR(255) DEFAULT NULL,
  `aadhar_number` VARCHAR(255) DEFAULT NULL,
  `ledger_code` VARCHAR(255) DEFAULT NULL,
  `ledger_group` VARCHAR(255) DEFAULT NULL,
  `credit_limit` DECIMAL(15, 2) DEFAULT NULL,
  `credit_days` INT DEFAULT NULL,
  `gst_applicable` VARCHAR(255) DEFAULT NULL,
  `gstin_no` VARCHAR(255) DEFAULT NULL,
  `gst_registered_name` VARCHAR(255) DEFAULT NULL,
  `gstin_registration_date` VARCHAR(255) DEFAULT NULL,
  `tds_applicable` VARCHAR(255) DEFAULT NULL,
  `wef_date` VARCHAR(255) DEFAULT NULL,
  `tds_certificate_no` VARCHAR(255) DEFAULT NULL,
  `tds_tax_percentage` DECIMAL(5, 2) DEFAULT NULL,
  `tds_category` VARCHAR(255) DEFAULT NULL,
  `tds_value_cab` DECIMAL(15, 2) DEFAULT NULL,
  `tan_number` VARCHAR(255) DEFAULT NULL,
  `msme_registered` VARCHAR(255) DEFAULT NULL,
  `msme_no` VARCHAR(255) DEFAULT NULL,
  `msme_type` VARCHAR(255) DEFAULT NULL,
  `status` VARCHAR(255) DEFAULT NULL,
  `group_id` BIGINT UNSIGNED DEFAULT NULL,
  `company_id` BIGINT UNSIGNED DEFAULT NULL,
  `organization_id` BIGINT UNSIGNED DEFAULT NULL,
  `remarks` TEXT DEFAULT NULL,
  `batch_no` VARCHAR(255) DEFAULT NULL,
  `user_id` BIGINT UNSIGNED DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
);

