<?php

namespace App\Helpers;

class TransactionReportHelper
{
    //Report filter routes mapping
    const FILTER_ROUTES = [
        ConstantHelper::SO_SERVICE_ALIAS => 'sale.order.report',
        ConstantHelper::SI_SERVICE_ALIAS => 'sale.invoice.report',
        ConstantHelper::SR_SERVICE_ALIAS => 'sale.return.report',
        ConstantHelper::MATERIAL_RETURN_SERVICE_ALIAS_NAME => 'material.return.report',
        ConstantHelper::MATERIAL_ISSUE_SERVICE_ALIAS_NAME => 'material.issue.report',
        ConstantHelper::MRN_SERVICE_ALIAS => 'material-receipt.order.report',
    ];
    const SO_TABLE_HEADERS = [
        [
            'name' => 'S. No',
            'field' => 'DT_RowIndex',
            'header_class' => '',
            'column_class' => '',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Series',
            'field' => 'book_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Doc No',
            'field' => 'document_number',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Date',
            'field' => 'document_date',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Location',
            'field' => 'store_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Customer',
            'field' => 'customer_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Currency',
            'field' => 'customer_currency',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Item Name',
            'field' => 'item_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Item Code',
            'field' => 'item_code',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Attributes',
            'field' => 'item_attributes',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'HSN',
            'field' => 'hsn_code',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'UOM',
            'field' => 'uom_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Order Qty',
            'field' => 'so_qty',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Item Rate',
            'field' => 'rate',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Discount',
            'field' => 'total_discount_amount',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Taxable Amt',
            'field' => 'taxable_amount',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Tax',
            'field' => 'tax_amount',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Total',
            'field' => 'total_item_amount',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Delivery Date',
            'field' => 'delivery_schedule',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'PWO Qty',
            'field' => 'pwo_qty',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Produced Qty',
            'field' => 'pslip_qty',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Invoiced Qty',
            'field' => 'invoice_qty',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Returned Qty',
            'field' => 'srn_qty',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Short Closed Qty',
            'field' => 'srn_qty',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Pending Qty',
            'field' => 'pending_qty',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Status',
            'field' => 'status',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => 'text-align:center',
            'column_style' => '',
        ],
    ];
    const SO_FILTERS = [
        [
            'colSpan' => 'auto',
            'label' => 'Customer',
            'id' => 'customer_filter',
            'requestName' => 'customer_id',
            'term' => 'customer',
            'value_key' => 'id',
            'label_key' => 'company_name',
            'type' => 'auto_complete'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Series',
            'id' => 'book_filter',
            'requestName' => 'book_id',
            'term' => 'report_so_book',
            'value_key' => 'id',
            'label_key' => 'book_code',
            'type' => 'auto_complete'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Doc No',
            'id' => 'doc_number_filter',
            'requestName' => 'document_number',
            'term' => 'report_so_documents',
            'value_key' => 'id',
            'label_key' => 'document_number',
            'type' => 'input_text'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Delivery Date',
            'id' => 'delivery_date_filter',
            'requestName' => 'delivery_date_range',
            'term' => '',
            'value_key' => '',
            'label_key' => '',
            'type' => 'date_range'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Item Category',
            'id' => 'item_cat_filter',
            'requestName' => 'item_category_id',
            'term' => 'category',
            'value_key' => 'id',
            'label_key' => 'name',
            'type' => 'auto_complete',
            'dependent' => ['item_sub_cat_filter', 'item_filter']
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Item Sub Category',
            'id' => 'item_sub_cat_filter',
            'requestName' => 'item_sub_category_id',
            'term' => 'subcategory',
            'value_key' => 'id',
            'label_key' => 'name',
            'type' => 'auto_complete',
            'dependent' => ['item_filter']
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Items',
            'id' => 'item_filter',
            'requestName' => 'item_id',
            'term' => 'report_items',
            'value_key' => 'id',
            'label_key' => 'item_name',
            'type' => 'auto_complete'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Status',
            'id' => 'doc_status_filter',
            'requestName' => 'doc_status',
            'term' => 'document_statuses',
            'value_key' => 'id',
            'label_key' => 'name',
            'type' => 'auto_complete'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Company',
            'id' => 'company_filter',
            'requestName' => 'company_id',
            'term' => 'companies',
            'value_key' => 'id',
            'label_key' => 'name',
            'type' => 'auto_complete',
            'dependent' => ['organization_filter']

        ],
        [
            'colSpan' => 'auto',
            'label' => 'Organization',
            'id' => 'organization_filter',
            'requestName' => 'organization_id',
            'term' => 'organizations',
            'value_key' => 'id',
            'label_key' => 'name',
            'type' => 'auto_complete',
            'dependent' => ['location_filter']
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Location',
            'id' => 'location_filter',
            'requestName' => 'location_id',
            'term' => 'location',
            'value_key' => 'id',
            'label_key' => 'store_name',
            'type' => 'auto_complete'
        ],
    ];
    const SI_TABLE_HEADERS = [
        [
            'name' => 'S. No',
            'field' => 'DT_RowIndex',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Series',
            'field' => 'book_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Doc No',
            'field' => 'document_number',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Date',
            'field' => 'document_date',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Location',
            'field' => 'store_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Customer',
            'field' => 'customer_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Currency',
            'field' => 'customer_currency',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Item Name',
            'field' => 'item_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Item Code',
            'field' => 'item_code',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Attributes',
            'field' => 'item_attributes',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'HSN',
            'field' => 'hsn_code',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'UOM',
            'field' => 'uom_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Invoice Qty',
            'field' => 'si_qty',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Item Rate',
            'field' => 'rate',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Discount',
            'field' => 'total_discount_amount',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Taxable Amt',
            'field' => 'taxable_amount',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Tax',
            'field' => 'tax_amount',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Total',
            'field' => 'total_item_amount',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],

        [
            'name' => 'Order No',
            'field' => 'so_no',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => 'text-align:center',
            'column_style' => '',
        ],
        [
            'name' => 'Order Dt',
            'field' => 'so_date',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => 'text-align:center',
            'column_style' => '',
        ],

        [
            'name' => 'Order Qty',
            'field' => 'so_qty',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Returned Qty',
            'field' => 'srn_qty',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Status',
            'field' => 'status',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => 'text-align:center',
            'column_style' => '',
        ],
    ];
    const SI_FILTERS = [
        [
            'colSpan' => 'auto',
            'label' => 'Customer',
            'id' => 'customer_filter',
            'requestName' => 'customer_id',
            'term' => 'customer',
            'value_key' => 'id',
            'label_key' => 'company_name',
            'type' => 'auto_complete'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Series',
            'id' => 'book_filter',
            'requestName' => 'book_id',
            'term' => 'report_so_book',
            'value_key' => 'id',
            'label_key' => 'book_code',
            'type' => 'auto_complete'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Doc No',
            'id' => 'doc_number_filter',
            'requestName' => 'document_number',
            'term' => 'report_so_documents',
            'value_key' => 'id',
            'label_key' => 'document_number',
            'type' => 'input_text'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Order No',
            'id' => 'order_no_filter',
            'requestName' => 'so_no',
            'term' => '',
            'value_key' => '',
            'label_key' => '',
            'type' => 'input_text',
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Order Dt',
            'id' => 'order_dt_filter',
            'requestName' => 'so_dt',
            'term' => '',
            'value_key' => '',
            'label_key' => '',
            'type' => 'date_range',
        ],

        [
            'colSpan' => 'auto',
            'label' => 'Item Category',
            'id' => 'item_cat_filter',
            'requestName' => 'item_category_id',
            'term' => 'category',
            'value_key' => 'id',
            'label_key' => 'name',
            'type' => 'auto_complete',
            'dependent' => ['item_sub_cat_filter', 'item_filter']
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Item Sub Category',
            'id' => 'item_sub_cat_filter',
            'requestName' => 'item_sub_category_id',
            'term' => 'subcategory',
            'value_key' => 'id',
            'label_key' => 'name',
            'type' => 'auto_complete',
            'dependent' => ['item_filter']
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Items',
            'id' => 'item_filter',
            'requestName' => 'item_id',
            'term' => 'report_items',
            'value_key' => 'id',
            'label_key' => 'item_name',
            'type' => 'auto_complete'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Status',
            'id' => 'doc_status_filter',
            'requestName' => 'doc_status',
            'term' => 'document_statuses',
            'value_key' => 'id',
            'label_key' => 'name',
            'type' => 'auto_complete'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Company',
            'id' => 'company_filter',
            'requestName' => 'company_id',
            'term' => 'companies',
            'value_key' => 'id',
            'label_key' => 'name',
            'type' => 'auto_complete',
            'dependent' => ['organization_filter']

        ],
        [
            'colSpan' => 'auto',
            'label' => 'Organization',
            'id' => 'organization_filter',
            'requestName' => 'organization_id',
            'term' => 'organizations',
            'value_key' => 'id',
            'label_key' => 'name',
            'type' => 'auto_complete',
            'dependent' => ['location_filter']
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Location',
            'id' => 'location_filter',
            'requestName' => 'location_id',
            'term' => 'location',
            'value_key' => 'id',
            'label_key' => 'store_name',
            'type' => 'auto_complete'
        ],
    ];

    const SR_TABLE_HEADERS = [
        [
            'name' => 'S. No',
            'field' => 'DT_RowIndex',
            'header_class' => '',
            'column_class' => '',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Series',
            'field' => 'book_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Doc No',
            'field' => 'document_number',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Date',
            'field' => 'document_date',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Location',
            'field' => 'store_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Customer',
            'field' => 'customer_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Currency',
            'field' => 'customer_currency',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Item Name',
            'field' => 'item_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Item Code',
            'field' => 'item_code',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Attributes',
            'field' => 'item_attributes',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'HSN',
            'field' => 'hsn_code',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'UOM',
            'field' => 'uom_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Returned Qty',
            'field' => 'sr_qty',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Item Rate',
            'field' => 'rate',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Discount',
            'field' => 'total_discount_amount',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Taxable Amt',
            'field' => 'taxable_amount',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Tax',
            'field' => 'tax_amount',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Total',
            'field' => 'total_item_amount',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Invoice No',
            'field' => 'si_no',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => 'text-align:center',
            'column_style' => '',
        ],
        [
            'name' => 'Invoice Dt',
            'field' => 'si_date',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => 'text-align:center',
            'column_style' => '',
        ],

        [
            'name' => 'Invoice Qty',
            'field' => 'si_qty',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Order No',
            'field' => 'so_no',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => 'text-align:center',
            'column_style' => '',
        ],
        [
            'name' => 'Order Dt',
            'field' => 'so_date',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => 'text-align:center',
            'column_style' => '',
        ],

        [
            'name' => 'Order Qty',
            'field' => 'so_qty',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Status',
            'field' => 'status',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => 'text-align:center',
            'column_style' => '',
        ],
    ];
    const SR_FILTERS = [
        [
            'colSpan' => 'auto',
            'label' => 'Customer',
            'id' => 'customer_filter',
            'requestName' => 'customer_id',
            'term' => 'customer',
            'value_key' => 'id',
            'label_key' => 'company_name',
            'type' => 'auto_complete'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Series',
            'id' => 'book_filter',
            'requestName' => 'book_id',
            'term' => 'report_so_book',
            'value_key' => 'id',
            'label_key' => 'book_code',
            'type' => 'auto_complete'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Doc No',
            'id' => 'doc_number_filter',
            'requestName' => 'document_number',
            'term' => 'report_so_documents',
            'value_key' => 'id',
            'label_key' => 'document_number',
            'type' => 'input_text'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Order No',
            'id' => 'order_no_filter',
            'requestName' => 'so_no',
            'term' => '',
            'value_key' => '',
            'label_key' => '',
            'type' => 'input_text',
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Order Dt',
            'id' => 'order_dt_filter',
            'requestName' => 'so_dt',
            'term' => '',
            'value_key' => '',
            'label_key' => '',
            'type' => 'date_range',
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Invoice No',
            'id' => 'invoice_no_filter',
            'requestName' => 'si_no',
            'term' => '',
            'value_key' => '',
            'label_key' => '',
            'type' => 'input_text',
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Invoice Dt',
            'id' => 'invoice_dt_filter',
            'requestName' => 'si_dt',
            'term' => '',
            'value_key' => '',
            'label_key' => '',
            'type' => 'date_range',
        ],

        [
            'colSpan' => 'auto',
            'label' => 'Item Category',
            'id' => 'item_cat_filter',
            'requestName' => 'item_category_id',
            'term' => 'category',
            'value_key' => 'id',
            'label_key' => 'name',
            'type' => 'auto_complete',
            'dependent' => ['item_sub_cat_filter', 'item_filter']
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Item Sub Category',
            'id' => 'item_sub_cat_filter',
            'requestName' => 'item_sub_category_id',
            'term' => 'subcategory',
            'value_key' => 'id',
            'label_key' => 'name',
            'type' => 'auto_complete',
            'dependent' => ['item_filter']
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Items',
            'id' => 'item_filter',
            'requestName' => 'item_id',
            'term' => 'report_items',
            'value_key' => 'id',
            'label_key' => 'item_name',
            'type' => 'auto_complete'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Status',
            'id' => 'doc_status_filter',
            'requestName' => 'doc_status',
            'term' => 'document_statuses',
            'value_key' => 'id',
            'label_key' => 'name',
            'type' => 'auto_complete'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Company',
            'id' => 'company_filter',
            'requestName' => 'company_id',
            'term' => 'companies',
            'value_key' => 'id',
            'label_key' => 'name',
            'type' => 'auto_complete',
            'dependent' => ['organization_filter']

        ],
        [
            'colSpan' => 'auto',
            'label' => 'Organization',
            'id' => 'organization_filter',
            'requestName' => 'organization_id',
            'term' => 'organizations',
            'value_key' => 'id',
            'label_key' => 'name',
            'type' => 'auto_complete',
            'dependent' => ['location_filter']
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Location',
            'id' => 'location_filter',
            'requestName' => 'location_id',
            'term' => 'location',
            'value_key' => 'id',
            'label_key' => 'store_name',
            'type' => 'auto_complete'
        ],
    ];
    const MATERIAL_RETURN_SERVICE_ALIAS_NAME_TABLE_HEADERS = [
        [
            'name' => 'S. No',
            'field' => 'DT_RowIndex',
            'header_class' => '',
            'column_class' => '',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Series',
            'field' => 'book_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Doc No',
            'field' => 'document_number',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Doc Type',
            'field' => 'return_type',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Date',
            'field' => 'document_date',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'From Location',
            'field' => 'from_store_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'To Location',
            'field' => 'to_store_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'From Sub Location',
            'field' => 'from_sub_store_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'To Sub Location',
            'field' => 'to_sub_store_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Vendor',
            'field' => 'vendor_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Requester',
            'field' => 'requester',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Currency',
            'field' => 'customer_currency',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Item Name',
            'field' => 'item_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Item Code',
            'field' => 'item_code',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Attributes',
            'field' => 'item_attributes',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'HSN',
            'field' => 'hsn_code',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'UOM',
            'field' => 'uom_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Returned Qty',
            'field' => 'qty',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Item Rate',
            'field' => 'rate',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        // [
        //     'name' => 'Discount',
        //     'field' => 'total_discount_amount',
        //     'header_class' => 'numeric-alignment',
        //     'column_class' => 'text-end',
        //     'header_style' => '',
        //     'column_style' => '',
        // ],
        // [
        //     'name' => 'Taxable Amt',
        //     'field' => 'taxable_amount',
        //     'header_class' => 'numeric-alignment',
        //     'column_class' => 'text-end',
        //     'header_style' => '',
        //     'column_style' => '',
        // ],
        // [
        //     'name' => 'Tax',
        //     'field' => 'tax_amount',
        //     'header_class' => 'numeric-alignment',
        //     'column_class' => 'text-end',
        //     'header_style' => '',
        //     'column_style' => '',
        // ],
        [
            'name' => 'Total',
            'field' => 'total_item_amount',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Issue No',
            'field' => 'mi_no',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => 'text-align:center',
            'column_style' => '',
        ],
        [
            'name' => 'Issue Dt',
            'field' => 'mi_date',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => 'text-align:center',
            'column_style' => '',
        ],

        [
            'name' => 'Issue Qty',
            'field' => 'mi_qty',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Status',
            'field' => 'status',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => 'text-align:center',
            'column_style' => '',
        ],
    ];
    const MATERIAL_RETURN_SERVICE_ALIAS_NAME_FILTERS = [
        [
            'colSpan' => 'auto',
            'label' => 'Vendor',
            'id' => 'vendor_filter',
            'requestName' => 'vendor_id',
            'term' => 'vendor',
            'value_key' => 'id',
            'label_key' => 'company_name',
            'type' => 'auto_complete'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Series',
            'id' => 'book_filter',
            'requestName' => 'book_id',
            'term' => 'report_so_book',
            'value_key' => 'id',
            'label_key' => 'book_code',
            'type' => 'auto_complete'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Doc No',
            'id' => 'doc_number_filter',
            'requestName' => 'document_number',
            'term' => 'report_so_documents',
            'value_key' => 'id',
            'label_key' => 'document_number',
            'type' => 'input_text'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'issue No',
            'id' => 'issue_no_filter',
            'requestName' => 'mi_no',
            'term' => '',
            'value_key' => '',
            'label_key' => '',
            'type' => 'input_text',
        ],
        [
            'colSpan' => 'auto',
            'label' => 'issue Dt',
            'id' => 'issue_dt_filter',
            'requestName' => 'mi_dt',
            'term' => '',
            'value_key' => '',
            'label_key' => '',
            'type' => 'date_range',
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Item Category',
            'id' => 'item_cat_filter',
            'requestName' => 'item_category_id',
            'term' => 'category',
            'value_key' => 'id',
            'label_key' => 'name',
            'type' => 'auto_complete',
            'dependent' => ['item_sub_cat_filter', 'item_filter']
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Item Sub Category',
            'id' => 'item_sub_cat_filter',
            'requestName' => 'item_sub_category_id',
            'term' => 'subcategory',
            'value_key' => 'id',
            'label_key' => 'name',
            'type' => 'auto_complete',
            'dependent' => ['item_filter']
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Items',
            'id' => 'item_filter',
            'requestName' => 'item_id',
            'term' => 'report_items',
            'value_key' => 'id',
            'label_key' => 'item_name',
            'type' => 'auto_complete'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Status',
            'id' => 'doc_status_filter',
            'requestName' => 'doc_status',
            'term' => 'document_statuses',
            'value_key' => 'id',
            'label_key' => 'name',
            'type' => 'auto_complete'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Company',
            'id' => 'company_filter',
            'requestName' => 'company_id',
            'term' => 'companies',
            'value_key' => 'id',
            'label_key' => 'name',
            'type' => 'auto_complete',
            'dependent' => ['organization_filter']
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Organization',
            'id' => 'organization_filter',
            'requestName' => 'organization_id',
            'term' => 'organizations',
            'value_key' => 'id',
            'label_key' => 'name',
            'type' => 'auto_complete',
            'dependent' => ['location_filter']
        ],
        [
            'colSpan' => 'auto',
            'label' => 'From Location',
            'id' => 'from_location_filter',
            'requestName' => 'from_location_id',
            'term' => 'location',
            'value_key' => 'id',
            'label_key' => 'store_name',
            'type' => 'auto_complete'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'To Location',
            'id' => 'to_location_filter',
            'requestName' => 'to_location_id',
            'term' => 'location',
            'value_key' => 'id',
            'label_key' => 'store_name',
            'type' => 'auto_complete'
        ],
    ];
    const MATERIAL_ISSUE_SERVICE_ALIAS_NAME_TABLE_HEADERS = [
        [
            'name' => 'S. No',
            'field' => 'DT_RowIndex',
            'header_class' => '',
            'column_class' => '',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Series',
            'field' => 'book_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Doc No',
            'field' => 'document_number',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Doc Type',
            'field' => 'issue_type',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Date',
            'field' => 'document_date',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'From Location',
            'field' => 'from_store_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'To Location',
            'field' => 'to_store_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'From Sub Location',
            'field' => 'from_sub_store_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'To Sub Location',
            'field' => 'to_sub_store_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Vendor',
            'field' => 'vendor_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Requester',
            'field' => 'requester',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Currency',
            'field' => 'customer_currency',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Item Name',
            'field' => 'item_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Item Code',
            'field' => 'item_code',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Attributes',
            'field' => 'item_attributes',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'HSN',
            'field' => 'hsn_code',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'UOM',
            'field' => 'uom_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Qty',
            'field' => 'qty',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Item Rate',
            'field' => 'rate',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        // [
        //     'name' => 'Discount',
        //     'field' => 'total_discount_amount',
        //     'header_class' => 'numeric-alignment',
        //     'column_class' => 'text-end',
        //     'header_style' => '',
        //     'column_style' => '',
        // ],
        // [
        //     'name' => 'Taxable Amt',
        //     'field' => 'taxable_amount',
        //     'header_class' => 'numeric-alignment',
        //     'column_class' => 'text-end',
        //     'header_style' => '',
        //     'column_style' => '',
        // ],
        // [
        //     'name' => 'Tax',
        //     'field' => 'tax_amount',
        //     'header_class' => 'numeric-alignment',
        //     'column_class' => 'text-end',
        //     'header_style' => '',
        //     'column_style' => '',
        // ],
        [
            'name' => 'Total',
            'field' => 'total_item_amount',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Returned Qty',
            'field' => 'mr_qty',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end pe-2_5',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Status',
            'field' => 'status',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => 'text-align:center',
            'column_style' => '',
        ],
    ];
    const MATERIAL_ISSUE_SERVICE_ALIAS_NAME_FILTERS = [
        [
            'colSpan' => 'auto',
            'label' => 'Vendor',
            'id' => 'vendor_filter',
            'requestName' => 'vendor_id',
            'term' => 'vendor',
            'value_key' => 'id',
            'label_key' => 'company_name',
            'type' => 'auto_complete'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Series',
            'id' => 'book_filter',
            'requestName' => 'book_id',
            'term' => 'report_so_book',
            'value_key' => 'id',
            'label_key' => 'book_code',
            'type' => 'auto_complete'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Doc No',
            'id' => 'doc_number_filter',
            'requestName' => 'document_number',
            'term' => 'report_so_documents',
            'value_key' => 'id',
            'label_key' => 'document_number',
            'type' => 'input_text'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Item Category',
            'id' => 'item_cat_filter',
            'requestName' => 'item_category_id',
            'term' => 'category',
            'value_key' => 'id',
            'label_key' => 'name',
            'type' => 'auto_complete',
            'dependent' => ['item_sub_cat_filter', 'item_filter']
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Item Sub Category',
            'id' => 'item_sub_cat_filter',
            'requestName' => 'item_sub_category_id',
            'term' => 'subcategory',
            'value_key' => 'id',
            'label_key' => 'name',
            'type' => 'auto_complete',
            'dependent' => ['item_filter']
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Items',
            'id' => 'item_filter',
            'requestName' => 'item_id',
            'term' => 'report_items',
            'value_key' => 'id',
            'label_key' => 'item_name',
            'type' => 'auto_complete'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Status',
            'id' => 'doc_status_filter',
            'requestName' => 'doc_status',
            'term' => 'document_statuses',
            'value_key' => 'id',
            'label_key' => 'name',
            'type' => 'auto_complete'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Company',
            'id' => 'company_filter',
            'requestName' => 'company_id',
            'term' => 'companies',
            'value_key' => 'id',
            'label_key' => 'name',
            'type' => 'auto_complete',
            'dependent' => ['organization_filter']
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Organization',
            'id' => 'organization_filter',
            'requestName' => 'organization_id',
            'term' => 'organizations',
            'value_key' => 'id',
            'label_key' => 'name',
            'type' => 'auto_complete',
            'dependent' => ['location_filter']
        ],
        [
            'colSpan' => 'auto',
            'label' => 'From Location',
            'id' => 'from_location_filter',
            'requestName' => 'from_location_id',
            'term' => 'location',
            'value_key' => 'id',
            'label_key' => 'store_name',
            'type' => 'auto_complete'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'To Location',
            'id' => 'to_location_filter',
            'requestName' => 'to_location_id',
            'term' => 'location',
            'value_key' => 'id',
            'label_key' => 'store_name',
            'type' => 'auto_complete'
        ],
    ];

    // MRN Headers and Filters
    const MRN_TABLE_HEADERS = [
        [
            'name' => 'S. No',
            'field' => 'DT_RowIndex',
            'header_class' => '',
            'column_class' => '',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Series',
            'field' => 'book_code',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'MRN No',
            'field' => 'document_number',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'MRN Date',
            'field' => 'document_date',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'PO NO',
            'field' => 'po_no',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Gate Entry No',
            'field' => 'ge_no',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'SO No',
            'field' => 'so_no',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'LOT No',
            'field' => 'lot_no',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Vendor',
            'field' => 'vendor_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Vendor Rating',
            'field' => 'vendor_rating',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Category',
            'field' => 'category_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Sub Category',
            'field' => 'sub_category_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Item type',
            'field' => 'item_type',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Sub type',
            'field' => 'sub_type',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Item',
            'field' => 'item_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Item Code',
            'field' => 'item_code',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Receipt Qty',
            'field' => 'receipt_qty',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Accepted Qty',
            'field' => 'accepted_qty',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Rejected Qty',
            'field' => 'rejected_qty',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Purchase Return Qty',
            'field' => 'pr_qty',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Purchase Return Rejected Qty',
            'field' => 'pr_rejected_qty',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Purchase Bill Qty',
            'field' => 'purchase_bill_qty',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Location',
            'field' => 'store_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Store',
            'field' => 'sub_store_name',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Rate',
            'field' => 'rate',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Basic Value',
            'field' => 'basic_value',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Item Discount',
            'field' => 'item_discount',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Header Discount',
            'field' => 'header_discount',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Item Amount',
            'field' => 'item_amount',
            'header_class' => 'numeric-alignment',
            'column_class' => 'text-end',
            'header_style' => '',
            'column_style' => '',
        ],
        [
            'name' => 'Status',
            'field' => 'status',
            'header_class' => '',
            'column_class' => 'no-wrap',
            'header_style' => 'text-align:center',
            'column_style' => '',
        ],
    ];
    const MRN_FILTERS = [
        [
            'colSpan' => 'auto',
            'label' => 'PO No',
            'id' => 'po_no',
            'requestName' => 'po_no',
            'term' => 'po_document_qt',
            'value_key' => 'id',
            'label_key' => 'document_number',
            'type' => 'auto_complete'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'GE No',
            'id' => 'gate_entry_no',
            'requestName' => 'gate_entry_no',
            'term' => 'gate_entry_no',
            'value_key' => 'id',
            'label_key' => 'document_number',
            'type' => 'input_text'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'SO No',
            'id' => 'so_no',
            'requestName' => 'so_no',
            'term' => 'report_so_documents',
            'value_key' => 'id',
            'label_key' => 'document_number',
            'type' => 'auto_complete'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'LOT No',
            'id' => 'lot_no',
            'requestName' => 'lot_no',
            'term' => 'lot_no',
            'value_key' => 'id',
            'label_key' => 'lot_no',
            'type' => 'input_text'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Item',
            'id' => 'item_filter',
            'requestName' => 'item_id',
            'term' => 'report_items',
            'value_key' => 'id',
            'label_key' => 'item_name',
            'type' => 'auto_complete'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Status',
            'id' => 'status',
            'requestName' => 'status',
            'term' => 'document_statuses',
            'value_key' => 'id',
            'label_key' => 'name',
            'type' => 'auto_complete'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Vendor',
            'id' => 'vendor',
            'requestName' => 'vendor',
            'term' => 'vendor_company_list',
            'value_key' => 'id',
            'label_key' => 'name',
            'type' => 'auto_complete'
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Item Category',
            'id' => 'm_category_id',
            'requestName' => 'm_category_id',
            'term' => 'category',
            'value_key' => 'id',
            'label_key' => 'name',
            'type' => 'auto_complete',
            'dependent' => ['m_subcategory_id', 'item_filter']
        ],
        [
            'colSpan' => 'auto',
            'label' => 'Item Sub Category',
            'id' => 'm_subcategory_id',
            'requestName' => 'm_subcategory_id',
            'term' => 'subcategory',
            'value_key' => 'id',
            'label_key' => 'name',
            'type' => 'auto_complete',
            'dependent' => ['item_filter']
        ],
    ];

    const FILTERS_MAPPING = [
        ConstantHelper::SO_SERVICE_ALIAS => self::SO_FILTERS,
        ConstantHelper::SI_SERVICE_ALIAS => self::SI_FILTERS,
        ConstantHelper::SR_SERVICE_ALIAS => self::SR_FILTERS,
        ConstantHelper::MATERIAL_RETURN_SERVICE_ALIAS_NAME => self::MATERIAL_RETURN_SERVICE_ALIAS_NAME_FILTERS,
        ConstantHelper::MATERIAL_ISSUE_SERVICE_ALIAS_NAME => self::MATERIAL_ISSUE_SERVICE_ALIAS_NAME_FILTERS,
        ConstantHelper::MRN_SERVICE_ALIAS => self::MRN_FILTERS
    ];
    const TABLE_HEADERS = [
        ConstantHelper::SO_SERVICE_ALIAS => self::SO_TABLE_HEADERS,
        ConstantHelper::SI_SERVICE_ALIAS => self::SI_TABLE_HEADERS,
        ConstantHelper::SR_SERVICE_ALIAS => self::SR_TABLE_HEADERS,
        ConstantHelper::MATERIAL_RETURN_SERVICE_ALIAS_NAME => self::MATERIAL_RETURN_SERVICE_ALIAS_NAME_TABLE_HEADERS,
        ConstantHelper::MATERIAL_ISSUE_SERVICE_ALIAS_NAME => self::MATERIAL_ISSUE_SERVICE_ALIAS_NAME_TABLE_HEADERS,
        ConstantHelper::MRN_SERVICE_ALIAS => self::MRN_TABLE_HEADERS
    ];
}
