ALTER TABLE `erp_groups` ADD COLUMN `edit` BOOLEAN NOT NULL DEFAULT TRUE AFTER `master_group_id`;
INSERT INTO `erp_groups` (`name`, `edit`, `created_at`, `updated_at`, `status`)
VALUES 
    ('Branch / Divisions', false, NOW(), NOW(), 'active'),
    ('Capital Account', false, NOW(), NOW(), 'active'),
    ('Reserves & Surplus', false, NOW(), NOW(), 'active'),
    ('Current Assets', false, NOW(), NOW(), 'active'),
    ('Bank Accounts', false, NOW(), NOW(), 'active'),
    ('Cash-in-Hand', false, NOW(), NOW(), 'active'),
    ('Deposits (Asset)', false, NOW(), NOW(), 'active'),
    ('Loans & Advances (Asset)', false, NOW(), NOW(), 'active'),
    ('Stock-in-Hand', false, NOW(), NOW(), 'active'),
    ('Account Receivable', false, NOW(), NOW(), 'active'),
    ('Current Liabilities', false, NOW(), NOW(), 'active'),
    ('Duties & Taxes', false, NOW(), NOW(), 'active'),
    ('GST', false, NOW(), NOW(), 'active'),
    ('TDS', false, NOW(), NOW(), 'active'),
    ('Other Statutory Dues', false, NOW(), NOW(), 'active'),
    ('Provisions', false, NOW(), NOW(), 'active'),
    ('Account Payable', false, NOW(), NOW(), 'active'),
    ('Direct Expenses', false, NOW(), NOW(), 'active'),
    ('Direct Incomes', false, NOW(), NOW(), 'active'),
    ('Fixed Assets', false, NOW(), NOW(), 'active'),
    ('Indirect Expenses', false, NOW(), NOW(), 'active'),
    ('Indirect Incomes', false, NOW(), NOW(), 'active'),
    ('Investments', false, NOW(), NOW(), 'active'),
    ('Loans (Liability)', false, NOW(), NOW(), 'active'),
    ('Bank OD A/c', false, NOW(), NOW(), 'active'),
    ('Secured Loans', false, NOW(), NOW(), 'active'),
    ('Unsecured Loans', false, NOW(), NOW(), 'active'),
    ('Misc. Expenses (ASSET)', false, NOW(), NOW(), 'active'),
    ('Purchase Accounts', false, NOW(), NOW(), 'active'),
    ('Sales Accounts', false, NOW(), NOW(), 'active'),
    ('Retained Earnings', false, NOW(), NOW(), 'active'),
    ('Suspense A/c', false, NOW(), NOW(), 'active'),
    ('Depreciation', false, NOW(), NOW(), 'active'),
    ('Assets', false, NOW(), NOW(), 'active'),
    ('Liabilities', false, NOW(), NOW(), 'active'),
    ('Expenses', false, NOW(), NOW(), 'active'),
    ('Incomes', false, NOW(), NOW(), 'active')
ON DUPLICATE KEY UPDATE 
    `edit` = VALUES(`edit`),
    `updated_at` = NOW(),
    `status` = VALUES(`status`);
